### ISSUE TITLE
Implementing calls to external routines

### ISSUE THREAD

**Issue by darozak** [howerj/embed#2]
As you know, we've been using embed to support a multiplayer space game in which player's use FORTH to program their drones.  We're at the point were we would like give the interpreter control of in game processes like flying the spacecraft.  What would be the best way to call external routines from within the FORTH environment?  

For example, we would like to have a FORTH command that tells the spacecraft to orbit a specific planet.   "4 Orbit" would tell the spacecraft to orbit the fourth planet from the sun.  "Orbit" would need to call an external C routine, which pulls 4 off the stack and relocates the ship to an orbit around Mars.  Is there a straight forward way of doing this?

Dave

**Comment by howerj** [comment]
That's great to hear, I've actually been working on adding that functionality to the library, if you take a look at the current repository there are test programs under 't/' that do extend the 'embed' VM and eForth to support floating point functionality which the VM does not natively support. 

It does this with a new instruction I added to the VM which can call a user supplied callback written in C, that callback can pull items off of the virtual machines stack and push them back on it with new functions available 'embed_push' and 'embed_pop'. It also contains code which evaluates code at startup, to define the new words can how the callback can trigger them.

You could either update the code you already have, or you could take the new embed library as a dependency and provide the needed callbacks. You should not have to modify the libraries source, just supply the library with the right options and callbacks. 

You should also look at the example code in 't/unix.c', which is an example that shows input and output callbacks being provided, which would allow you to yield the virtual machine after exhausting string input. You could use this mechanism to evaluate strings and then yield after no more input is available by supplying the right callback, and writing the output to an arbitrary buffer by supplying the right callbacks and data instead of modifying the code like you had to do the first time you integrated the project. 

This means that you should just have to update the library instead and you should get any updates I have made instead of having to adapt the code to your needs.

I have yet to document everything, only the example programs and docstrings for the library (in 'embed.h') have been written. But look into the test programs and see if they make sense. I will be able to help your either way you choose to proceed, although probably not this week or the beginning of next week as I'll be quite busy, becoming available again after that.

Thanks!

**Comment by darozak** [comment]
Thanks!  This is very encouraging.  Right now we're working to track orbits within the game.  However, as soon as the ships are situated in space, we'll begin constructing functions that allow the spacecraft to query and affect the orbital databases.  At that point we'll need to call upon your new routines to pass data and control between C and the FORTH interpreter.  I'll keep you posted and reach out to you as questions arise.

**Comment by howerj** [comment]
Ok, that's great. Now would be a good time to fork the repository and import it into your project.

**Comment by darozak** [comment]
Richard, 
As an aside, can you recommend any good online FORTH users communities to plug into?

**Comment by howerj** [comment]
I think ForthHub is quite good, see:
https://github.com/ForthHub/discussion/blob/master/README.md

Apart from that I'm mostly self taught. If you find any others let me know.

Also, I'm currently working on a branch 'mmu' which will make a fair few changes to the API, but I'm not going to merge it for a while. You might not like the changes, and seeing as your one of the primary users, feel free to give feedback and make suggestions.

**Comment by darozak** [comment]
Thanks Richard.  I'll check out ForthHub and try to keep an eye on what you're developing in the mmu branch.

**Comment by darozak** [comment]
I just forked the current version of embed into my repository (https://github.com/Darwin-River/embed) so we can build Ex Machinis around that.  I just want to confirm that this version of embed has what we need to implement the C callbacks.

**Comment by howerj** [comment]
Yes, the latest version, which you've forked, will work.

**Comment by howerj** [comment]
If there isn't anything else on this topic, I'll close this issue?

**Comment by darozak** [comment]
Hi Richard.  We're in the process of integrating the latest version of Embed into Ex Machinis.  I'll let you know if we have any issues.  But you can definitely close out this particular thread.  Thanks for all your help!!

Dave

**Comment by howerj** [comment]
Cheers!
