### ISSUE TITLE
How do you clean up the dictionary?

### ISSUE THREAD

**Issue by darozak** [howerj/embed#5]
Hi Richard.  I just have a quick question for you.  How does a user remove words from a dictionary after they have been added?  I think some versions of FORTH have a flush command that resets the dictionary pointer. Do you have any suggestions on how to implement this in embed?

**Comment by howerj** [comment]
Hi!

If you check our 't/unit.fth', line 92, a word called 'marker' is defined. This is a defining word which creates a new word, this word when called erases everything at the dictionary until that point.

So a usage would be:

     : ex1 2 2 + . ;
     marker XXX
     : ex2 3 3 + . ;
     XXX

After running this 'ex1' would still be defined and 'ex2' would have been removed from the dictionary. There are some limitations to this however, calling the created marker deletes all words after the marker has been deleted, and there are some potentially bad interactions if multiple vocabularies are used.

Thanks,
Richard

**Comment by darozak** [comment]
Thanks Richard.  This is very helpful.  I'll give it a try.

**Comment by darozak** [comment]
Is there a variable that points to the top of the dictionary?

**Comment by howerj** [comment]
There isn't a user accessible variable that does, however you can use 'here' to determine the current location of the dictionary pointer and 'allot' to move the dictionary pointer back (it accepts negative values which moves the dictionary pointer back). You can see this in the implementation of marker. There is nothing stopping you adding in access to that hidden variable (called 'cp' in 'embed.fth') if you wanted.

The reason it's not accessible is because there is no standard name for this variable in Forth.
