### ISSUE TITLE
Do you have a memory map for the 16-bit VM?

### ISSUE THREAD

**Issue by darozak** [howerj/embed#6]
Hi Richard.  Do you happen to have a memory map for the VM to show where the the dictionary, stacks, and other internal components are located?  Also, what is the anatomy of a FORTH definition?  For example, do definitions use a three character name field followed by link, code pointer, and parameter fields?  I'm working on developing a tutorial for Ex Machinis players and want to start digging into memory use and configuration.

Dave

**Comment by howerj** [comment]
Hi Dave,

There is a complete description of the system in the file 'embed.fth' - it describes all of the internals of the eForth image that is constructed. However, to answer your questions more directly I will need to know which version of the embed VM and which image you plan on using. I may have changed the way things have worked since you forked off the repository.

For the current VM:
* The initial registers are set from the first memory locations; the initial program counter is loaded from memory address zero, the top of the stack from one, the return stack pointer from two, and the variable stack pointer from memory location three. They are kept in those registers and saved back to memory only when the VM exits. The actual virtual machine implementation is less than 100 LoC, so should be fairly easy to understand.
* I don't think any modern Forth implementations use three character name fields, only ancient versions. The way dictionary entries are stored in this Forth is not ideal, most Forth implementations store the names and the code separately, but in this one they are stored together as part of the word definition. However, there is a diagram and a description within 'embed.fth' that describes the word layout:

```
\ A word list looks like this..
\
\	   ^
\	   |
\	.-----.-----.-----.----.----
\	| PWD | NFA | CFA | ...         <--- Word definition
\	.-----.-----.-----.----.----
\	   ^        ^                ^
\	   |        |--Word Body...  |
\	   |
\	.-----.-----.-----.----.----
\	| PWD | NFA | CFA | ...
\	.-----.-----.-----.----.----
\	^                 ^
\	|---Word Header---|
\
\

```

**Comment by darozak** [comment]
Thanks Richard! Apologies for not finding this on my own. There's a wealth of information in embed.fth.  I'll reference this file in our specific installation for details and let you know if I have any questions. Thanks for being so supportive!

Dave

**Comment by howerj** [comment]
No problem, let me know if you find any problems with the documentation, I'm not very good at proof reading my own work. I'll mark this as closed unless you have any more questions?

**Comment by darozak** [comment]
Thanks! I'm good. You can close the issue.On Sep 10, 2019 3:59 PM, Richard James Howe <notifications@github.com> wrote:No problem, let me know if you find any problems with the documentation, I'm not very good at proof reading my own work. I'll mark this as closed unless you have any more questions?
